model:
  name: "KNO1D"
  channels: 32
  modes: 64
  depths: 4
  resolution: 1024

data:
  name: "burgers1d"
  root_dir: "./dataset"
  in_channels: 1
  out_channels: 1
  train:
    num_samples: 1000
  test:
    num_samples: 200
  batch_size: 8
  step: 32

optimizer:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001

summary:
  summary_dir: "./summary_dir/"
  test_interval: 10
